:toc:
== [.underline]#Ходоки#

=== Получить ходоков

*Запрос:*

GET https://dev.waadsu.com/api/v2/walkers 

\include::insert x-access-token.adoc[]
xref:x-access-token.adoc[token]

* *Ответ*:  

    ** 200

        {

                            type: 'object',
                            properties: {
                                user_id: { type: 'int' },
                                bonus_code: { type: 'string' },
                                backpack: {
                                    type: ['object', 'null'],
                                    properties: {
                                        name: { type: 'string' },
                                        connection_type: { type: 'string', enum: ['WIFI', 'BLE']},
                                        control_card: { type: ['string', 'null']},
                                        version: { type: 'string' },
                                        screen_size: { type: 'string'}
                                    }
                                },
                                docsUploaded: { type: 'boolean' },
                                activated_code: { type: 'string' },
                                isVerified: { type: 'boolean'},
                                balance: {
                                    type: 'object',
                                    properties: {
                                        currency: { type: 'string', enum: ['RUB', 'EUR', 'USD', 'GWAS']] },
                                        amount: { type: 'number' }
                                    }
                                }
                            }
        }

        ГДЕ:
        
        user_id - уникальный идентификатор пользователя
        bonus_code - реферальный код
        docsUploaded - подтверждение о загрузке всех документов
        activated_code - код активации
        isVerified - свидетельствование о подтверждении ходака

        
        BACKPACK - сведения о рюкзаке

        name - название рюкзака
        connection_type - тип соединения с рюкзаком
        control_card - модель платы управления
        version - версия прошивки
        screen_size - размер матрицы

        BALANCE - баланс ходака
        
        currency - тип валюты
        amount - количество денежных единиц в указанной валюте
        

        ** 403

            Неверный токен: { message: "Invalid Token" }

            Недействительный пользователь: { message: 'Invalid user' }

            Недействительный ходок: { message:"Invalid walker" }

            Нет разрешения на выполнение данной операции: { message: "Not enough permissions" }

        ** 400

            Не определена валюта у ходака: {message: "Currency not defined"}
        
        ** 500

            Рюкзак ходака не найден: {message: "Backpack not found"}

---

=== Добавление подробной информации о ходоке
*Запрос:*

POST https://dev.waadsu.com/api/v2/walker/questionary

include::insert x-access-token.adoc[]

* Body :

    {
                            age: { type: 'integer', minimum: 0 },
                            backpackIs: { type: 'integer', enum: [1,2]},
                            earningMoneyIdea: { type: 'string' },
                            favoriteColors: { type: 'array', items: { type: 'string' }},
                            favoriteTransport: { type: 'integer', enum: [1,2,3,4]},
                            femaleFriendsCount: { type: 'integer', minimum: 0 },
                            height: { type: 'number' },
                            interestInTheBonus: { type: 'boolean' },
                            lifestyle: { type: 'integer', enum: [1,2,3]},
                            maleFriendsCount: { type: 'integer', minimum: 0 },
                            sex: { type: 'integer', enum: [1,2]},
                            timeOnTheStreet: { type: 'integer', enum: [1,2,3]},
                            weight: { type: 'number', minimum: 0 }
    }

** Required parameters

        'age', 'backpackIs', 'earningMoneyIdea', 'favoriteColors', 'favoriteTransport','femaleFriendsCount', 'height', 'interestInTheBonus', 'lifestyle', 'maleFriendsCount', 'sex', 'timeOnTheStreet','weight'


        



include::doc2.adoc[]
